#!/bin/bash
set -e

export NOSHELL=true

ip=$(ifconfig  | grep inet | awk '{print $2}' | head -1 | awk 'BEGIN{FS=":"}{print $2}')

echo "
-------------------------------------
     Make your changes, and hit F5
          this just works \o/

                $ip
-------------------------------------
"

cd /source

bash -l
